"""Creacion de las entidades

Revision ID: 0503591c7365
Revises: 
Create Date: 2026-06-28 13:47:20.580061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0503591c7365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companies',
    sa.Column('id_company', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_company'),
    sa.UniqueConstraint('name')
    )
    op.create_table('repositories',
    sa.Column('id_repository', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_repository'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('name')
    )
    op.create_table('type_movements',
    sa.Column('id_type_movement', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_type_movement'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('purchase_price', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('sale_price', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id_category'], ),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_table('suppliers',
    sa.Column('id_supplier', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('telephone', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id_company', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_company'], ['companies.id_company'], ),
    sa.PrimaryKeyConstraint('id_supplier')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id_role'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inventories',
    sa.Column('id_inventory', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_repository', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.ForeignKeyConstraint(['id_repository'], ['repositories.id_repository'], ),
    sa.PrimaryKeyConstraint('id_inventory')
    )
    op.create_table('movements',
    sa.Column('id_movement', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_supplier', sa.Integer(), nullable=False),
    sa.Column('id_type_movement', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_repository', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.ForeignKeyConstraint(['id_repository'], ['repositories.id_repository'], ),
    sa.ForeignKeyConstraint(['id_supplier'], ['suppliers.id_supplier'], ),
    sa.ForeignKeyConstraint(['id_type_movement'], ['type_movements.id_type_movement'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_movement')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movements')
    op.drop_table('inventories')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('products')
    op.drop_table('type_movements')
    op.drop_table('roles')
    op.drop_table('repositories')
    op.drop_table('companies')
    op.drop_table('categories')
    # ### end Alembic commands ###
