"""creacion de movement_details

Revision ID: d7801882f922
Revises: fabfae45b388
Create Date: 2026-07-04 14:50:29.883623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7801882f922'
down_revision = 'fabfae45b388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement_details',
    sa.Column('id_movement_detail', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_movement', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_movement'], ['movements.id_movement'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_movement_detail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement_details')
    # ### end Alembic commands ###
