"""Agregacion de sale detail

Revision ID: fabfae45b388
Revises: 0503591c7365
Create Date: 2026-07-04 11:03:30.505019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabfae45b388'
down_revision = '0503591c7365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('movements_id_product_fkey'), type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('id_product')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_product', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('movements_id_product_fkey'), 'products', ['id_product'], ['id_product'])

    # ### end Alembic commands ###
